version: '3'

volumes:
  db-data:

services:
  db:
    image: postgres:14
    container_name: test-db
    volumes:
      - db-data:/var/lib/postgresql/test_db_development/data
    ports:
      - '54329:5432'
      - '5555:5555'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
